name: exchanger_server
description: A gRPC server for exchanger flutter app.
version: 1.0.0
homepage: https://github.com/cychiang/exchanger-server
author: Casper CY Chiang <cychiang0823@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  grpc: '^0.4.1'
  protobuf: '^0.7.0'
  async: '>=1.13.3 <3.0.0'
  open_exchange_rates: '^0.1.1'

dev_dependencies:
  test: '^0.12.30'
